name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug paths
      run: |
        echo "Workspace: ${{ github.workspace }}"
        ls -la ${{ github.workspace }}

    - name: Lint check with clang-tidy
      run: |
        echo "Running clang-tidy..."
        find ./src -type f \( -name "*.c" -o -name "*.h" \) -print0 | xargs -0 clang-tidy -- -std=c11
      working-directory: ${{ github.workspace }}

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S .
      working-directory: ${{ github.workspace }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}
      working-directory: ${{ github.workspace }}

    - name: Run Unit Tests
      run: ctest --output-on-failure --build-config ${{ matrix.build_type }}
      working-directory: ${{ github.workspace }}/build
