name: CMake on Unix/Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        include:
          - c_compiler: gcc
            cpp_compiler: g++

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Remove previous build directory
      run: |
        rm -rf ${{ github.workspace }}/cmake-build-debug

    - name: Cache CMake files
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/cmake-build-debug
        key: linux-cmake-${{ github.ref_name }}-${{ matrix.build_type }}
        restore-keys: |
          linux-cmake-

    - name: Install dependencies
      run: sudo apt-get install -y clang-tidy cmake gcc g++

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/cmake-build-debug" >> "$GITHUB_OUTPUT"

    - name: Lint check with clang-tidy
      run: |
        clang-tidy \
        $(find ${{ github.workspace }}/src -name '*.c') \
        -p ${{ steps.strings.outputs.build-output-dir }}

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Install the built code
      run: cmake --install ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} --prefix ${{ github.workspace }}/install

    - name: Verify installation directory
      run: |
        echo "Listing installed files:"
        ls -l ${{ github.workspace }}/install
        if [ ! -d "${{ github.workspace }}/install" ] || [ -z "$(ls -A ${{ github.workspace }}/install)" ]; then
          echo "Error: Install directory is empty or does not exist."
          exit 1
        fi

    - name: Create binary package
      run: |
        mkdir -p ${{ github.workspace }}/packages
        tar -czf ${{ github.workspace }}/packages/myproject-${{ matrix.build_type }}.tar.gz -C ${{ github.workspace }}/install .

    - name: Upload binary package
      uses: actions/upload-artifact@v3
      with:
        name: binary-package-${{ matrix.build_type }}
        path: ${{ github.workspace }}/packages/myproject-${{ matrix.build_type }}.tar.gz

    - name: Run unit tests
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --output-on-failure --build-config ${{ matrix.build_type }}

    - name: Upload build artifacts
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: ${{ steps.strings.outputs.build-output-dir }}
