name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@v4

    - name: Debug Paths
      shell: bash
      run: |
        echo "Workspace: ${{ github.workspace }}"
        ls -al ${{ github.workspace }}

    - name: Remove previous build directory
      shell: bash
      run: |
        if [ -d "${{ github.workspace }}/cmake-build-debug" ]; then
          rm -rf "${{ github.workspace }}/cmake-build-debug"
        fi

    - name: Cache CMake files
      uses: actions/cache@v3
      with:
        path: ./cmake-build-debug
        key: ${{ runner.os }}-cmake-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-cmake-

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/cmake-build-debug" >> "$GITHUB_OUTPUT"

    - name: Lint check with clang-tidy
      shell: bash
      run: |
        find ./src -name "*.c" -o -name "*.h" | xargs clang-tidy -- -std=c11

    - name: Configure CMake
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
              -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
              -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Run unit tests
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --output-on-failure --build-config ${{ matrix.build_type }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: ${{ steps.strings.outputs.build-output-dir }}
